/*
 * modules.c --- automatically generated by Apache
 * configuration script.  DO NOT HAND EDIT!!!!!
 */

#include "httpd.h"
#include "http_config.h"

extern module core_module;
extern module env_module;
extern module config_log_module;
extern module mime_module;
extern module dir_module;
extern module cgi_module;
extern module alias_module;
extern module rewrite_module;
extern module access_module;
extern module auth_module;
extern module expires_module;
extern module php5_module;

/*
 *  Modules which implicitly form the
 *  list of activated modules on startup,
 *  i.e. these are the modules which are
 *  initially linked into the Apache processing
 *  [extendable under run-time via AddModule]
 */
module *ap_prelinked_modules[] = {
  &core_module,
  &env_module,
  &config_log_module,
  &mime_module,
  &dir_module,
  &cgi_module,
  &alias_module,
  &rewrite_module,
  &access_module,
  &auth_module,
  &expires_module,
  &php5_module,
  NULL
};

/*
 *  Modules which initially form the
 *  list of available modules on startup,
 *  i.e. these are the modules which are
 *  initially loaded into the Apache process
 *  [extendable under run-time via LoadModule]
 */
module *ap_preloaded_modules[] = {
  &core_module,
  &env_module,
  &config_log_module,
  &mime_module,
  &dir_module,
  &cgi_module,
  &alias_module,
  &rewrite_module,
  &access_module,
  &auth_module,
  &expires_module,
  &php5_module,
  NULL
};

